# Generated by Django 4.0 on 2021-12-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_announcements_alter_enrollments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['course', '-created_at'], 'verbose_name': 'Anúncio', 'verbose_name_plural': 'Anúncios'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['announcement', 'created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
    ]
