# Generated by Django 4.0 on 2021-12-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_announcements_options_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_announcements', to='courses.course', verbose_name='Curso'),
        ),
    ]
