# Generated by Django 4.0 on 2021-12-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread_alter_thread_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_reply', to='forum.thread'),
        ),
    ]
