# Generated by Django 4.0 on 2021-12-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enrollments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollments',
        ),
    ]
